### ISSUE TITLE
Update the dependency of react router to 3.xx

### ISSUE THREAD

**Issue by ottoo** [burczu/react-router-role-authorization#10]
We were using react-router 3.0.2 and got this error (mismatching history.js) with react-router-role-authorization because it has a dependency to react-router 2 by ^2.5.1.

/node_modules/react-router/es/createRouterHistory.js Cannot read property 'name' of null

Could you upgrade the router to 3.xx?

**Comment by burczu** [comment]
thanks for this issue - I will take a look at this ASAP

**Comment by burczu** [comment]
I've just moved react-router dependency to `peedDependencies` so from now on, this lib has no dependencies at all. I hope it will fix your issue.
