### ISSUE TITLE
NPM package is out of date and missing features

### ISSUE THREAD

**Issue by aqualad** [burczu/react-router-role-authorization#6]
The [NPM package for this project](https://www.npmjs.com/package/react-router-role-authorization) says that its latest release is `1.0.0`, but it's missing the "custom handling of unauthorized access" feature that allows users to overload `handleUnauthorizedRole`.  

I believe it's currently at 549efbe241ac3db6d06f7951077d653353e62b4e but the Github repo doesn't have any tags to validate the release.

Creating tags in Github and updating the NPM package would resolve these issues.

**Comment by burczu** [comment]
yes, it's not on npm yet because it is not working as it should - I'm working on it now

**Comment by burczu** [comment]
ok, I've just published version 1.1.0 to npm (tagged as latest) - it allows overriding `handleUnauthorizedRole`!
